#!/usr/bin/env zsh

# ==============================================================================
# Configuration
# ==============================================================================

MACOS_SETUP_DIR=~/projects/perso/provision

# ==============================================================================
# Directory Operations
# ==============================================================================

function mkcd() { mkdir -p "$@" && cd "$_"; }

alias cd..="cd .."
alias ..="cd .."
alias ls="ls -a"

# ==============================================================================
# Git Workflow
# ==============================================================================

function lazy-git() {
  if [[ -z "$1" ]]; then
    echo "Error: commit message required"
    return 1
  fi

  git add . && \
  (git commit -q -a -m "$1" || (git add . && git commit -q -a -m "$1")) && \
  git push -q
}

# Shared helper: generate a conventional commit message from the currently
# staged diff (cwd must already be inside the target repo, changes staged).
function _dp_commit_msg() {
  git diff --cached | copilot --silent --model 'claude-haiku-4.5' --prompt \
    "Output exactly one conventional commit message for this staged diff.
Format: <type>(<scope>): <description>
Allowed types: feat, fix, chore, refactor, docs, style, test, ci.
No explanation, no preamble, no quotes, no markdown. One line only." \
    | grep -oE '^(feat|fix|chore|refactor|docs|style|test|ci)(\([^)]+\))?: .+'
}

# Runs ansible-galaxy (only when requirements.yml changed) then the playbook.
# Assumes cwd is the target repo root.
function dp-provision() {
  local cache_dir="${HOME}/.cache/dev-provision"
  mkdir -p "${cache_dir}"
  local cache_file="${cache_dir}/requirements-$(basename "$PWD").yml"

  if [[ -f requirements.yml ]] && ! cmp -s requirements.yml "${cache_file}" 2>/dev/null; then
    ansible-galaxy install -r requirements.yml || return 1
    cp requirements.yml "${cache_file}"
  fi

  ansible-playbook main.yml --diff --limit $(hostname)
}

function dp-push() {
  local commit_msg="${1}"

  if [[ ! -d "${MACOS_SETUP_DIR}/dev-provision" ]]; then
    echo "Error: ${MACOS_SETUP_DIR}/dev-provision not found" >&2
    return 1
  fi

  (
    cd "${MACOS_SETUP_DIR}/dev-provision" || exit 1

    git add .
    if git diff --cached --quiet; then
      echo "dev-provision: nothing to commit, skipping."
      exit 0
    fi

    if [[ -z "${commit_msg}" ]]; then
      commit_msg=$(_dp_commit_msg)
      if [[ -z "${commit_msg}" ]]; then
        print -P "%F{red}Error: failed to generate commit message%f" >&2
        print -P "%F{yellow}Hint: make sure changes are staged (git add) and copilot is available%f" >&2
        exit 1
      fi
      echo "Commit message generated by Copilot: [${commit_msg}]"
    fi

    lazy-git "${commit_msg}" && dp-provision
  )
}

# ==============================================================================
# Development Helpers
# ==============================================================================

# dp-edit — open the dev-provision project, or delegate a natural-language request to
# Copilot CLI and auto-deploy:
#   dp-edit                          → open project in IntelliJ IDEA
#   dp-edit 'add alias for docker'   → Copilot edits the repo, then dp-push provisions the machine
function dp-edit() {
  if [[ $# -eq 0 ]]; then
    idea "${MACOS_SETUP_DIR}"
    return
  fi

  local request="$*"

  if [[ ! -d "${MACOS_SETUP_DIR}/dev-provision" ]]; then
    print -P "%F{red}Error: ${MACOS_SETUP_DIR}/dev-provision not found%f" >&2
    return 1
  fi

  cd "${MACOS_SETUP_DIR}/dev-provision"
  print -P "%F{cyan}Launching Copilot for: ${request}%f"
  copilot "$request"

  local exit_code=$?
  if [[ $exit_code -ne 0 ]]; then
    print -P "%F{red}Copilot exited with error (code ${exit_code}) — skipping push%f" >&2
    return $exit_code
  fi

  dp-push
}
alias notes="idea ${MACOS_SETUP_DIR}/notes"

# ==============================================================================
# Cheat Sheets
# ==============================================================================

function cheat() {
  local sheets=(~/.docs/*-cheat-sheet.md(N))

  if [[ $# -eq 0 ]]; then
    print "available cheat sheets:"
    for f in $sheets; do
      print "  $(basename $f -cheat-sheet.md)"
    done
    return
  fi

  local found=0
  for pattern in "$@"; do
    for f in $sheets; do
      if [[ $(basename $f) == *$pattern* ]]; then
        bat --style=plain "$f"
        found=1
      fi
    done
  done

  [[ $found -eq 0 ]] && print "no cheat sheet matching '$*'" >&2
}

function _cheat() {
  local -a sheets
  sheets=(~/.docs/*-cheat-sheet.md(N))
  sheets=(${sheets:t:s/-cheat-sheet.md//})
  compadd $sheets
}
compdef _cheat cheat

alias gitmess="cat ~/.gitmessage"
alias zshshorcut="open http://www.geekmind.net/2011/01/shortcuts-to-improve-your-bash-zsh.html"
alias good-readme="open https://github.com/othneildrew/Best-README-Template"

# ==============================================================================
# Tool Aliases
# ==============================================================================

alias upgrade="brew upgrade && mise upgrade"
alias diff="grc diff"
alias yaml="highlight --force --syntax yaml"
